# Generated by Django 3.0.6 on 2020-05-20 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('data_evento', models.DurationField()),
                ('data_criacao', models.DateField(auto_now=True)),
            ],
            options={
                'db_table': 'evento',
            },
        ),
    ]
